apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app_type: grav-gitsync
      cms: grav

images:
  - name: grav-gitsync
    newName: kalos/grav-gitsync
    newTag: "1.3"

resources:
  - service.yaml
  - deployment.yaml
  - ingress.yaml
