apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.14.6/manifests/install.yaml

patches:
  - path: argocd-cm-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-cm
      labelSelector: "app.kubernetes.io/name=argocd-cm"
  - path: argocd-cd-repo-server-ksops-patch.yaml
    target:
      kind: Deployment
      version: v1
      name: argocd-repo-server
      labelSelector: "app.kubernetes.io/name=argocd-repo-server"
