apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

labels:
  - pairs:
      env: staging

resources:
- ../../base

patches:
  - path: deployment.yaml
  - path: ingress.yaml

generators:
  - ./secret-gen-ght.yaml
  - ./secret-gen-gitsync-conf.yaml
