# how to crypt a secret:
# - create secret
#   kubectl create secret generic backend-user --from-literal=github_token='aa' -o yaml
# - crypt
#   sops -e secret.yaml > secret.enc.yaml
# - define KSOPS kustomize Generator
#   THIS FILE
# - add generators in kustomization.yaml
#   generators:
#     - ./secret-generator.yaml
# - generate yaml
#   kustomize build --enable-alpha-plugins --enable-exec overlays/staging/
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: ksops-secret-gen-gitsync_conf
  annotations:
    config.kubernetes.io/function: |
        exec:
          # if the binary is in your PATH, you can do
          # path: ksops
          # otherwise, path should be relative to manifest files, like
          path: /opt/kustomize/viaduct.ai/v1/ksops/ksops
files:
  - ./secret-gitsync-conf.enc.yaml
