# how to crypt a secret:
# - create secret
#   kubectl create secret generic backend-user --from-literal=github_token='aa' -o yaml
# - crypt
#   sops -e secret.yaml > secret.enc.yaml
# - define KSOPS kustomize Generator
#   THIS FILE
# - add generators in kustomization.yaml
#   generators:
#     - ./secret-generator.yaml
# - generate yaml
#   kustomize build --enable-alpha-plugins --enable-exec overlays/staging/
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: ksops-secret-gen-github_token
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - ./secret-ght.enc.yaml
